sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

env:
  DOCKER_COMPOSE_VERSION: 1.4.2
  DOCKER_EMAIL: gianafrancisco@gmail.com
  DOCKER_USERNAME: fgiana
  DOCKER_PASSWORD: ********

after_install:
  - docker build -t fgiana/tesisEmiliano .
  - docker run -name tesis -d fgiana/tesisEmiliano
  - docker ps
  - docker port tesis

